### ISSUE TITLE
[optimize] [dev] Expected behavior of `pllmod_opt_optimize_branch_lengths_local` when radius is 0?

### ISSUE THREAD

**Issue by bcclaywell** [ddarriba/pll-modules#15]
I was hoping I could pass a radius of 0 to `pllmod_opt_optimize_branch_lengths_local` to optimize only the edge between `tree` and `tree->back`, but I think the actual behavior is unintended. 

From what I can tell, the [first call to `recomp_iterative`](https://github.com/ddarriba/pll-modules/blob/7db0c37403dd07e77b3650330fd62d07b558c16f/src/optimize/pll_optimize.c#L1037) on `tree` would halt after optimizing that edge when it gets to [this if statement on L881](https://github.com/ddarriba/pll-modules/blob/7db0c37403dd07e77b3650330fd62d07b558c16f/src/optimize/pll_optimize.c#L881) and `radius` is 0. The [second call to `recomp_iterative`](https://github.com/ddarriba/pll-modules/blob/7db0c37403dd07e77b3650330fd62d07b558c16f/src/optimize/pll_optimize.c#L1045) on `tree->back` would be passed a radius of -1, which won't halt at the if statement, and I think instead it would go on to continue calling itself until that entire subtree was optimized.

Should the if statement on L881 be `if (radius > 0 && tr_q && tr_z)` instead?

**Comment by ddarriba** [comment]
Thanks for reporting this issue! Actually we detected that bug a few days ago, and it is already fixed locally. We will push the fix tomorrow.
