### ISSUE TITLE
pll.h not found

### ISSUE THREAD

**Issue by zigq** [ddarriba/pll-modules#21]
When I tried to compile and install module with the bundled version `libpll', the 'configure: error: pll.h not found' always show up.

**Comment by Pbdas** [comment]
Hi @zigq!
Did you clone the repo recursively?

If not you can still do it via `git submodule update --init --recursive`

Also, you can try to build using cmake instead:
`mkdir build && cd build && cmake .. && make`

**Comment by zigq** [comment]
Thank you!
